# tomcat
server:
  port: 9000
spring:
  application:
    name: kitty-generator
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.136.41.45:3306/kitty?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
      username: root
      password: 123456
beetl:
  templatesPath: templates